version: "3.1"
services:
  proxy:
    image: nginx:1.19.5-alpine
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  back:
    build: crud_service
    volumes: 
      - ./bicicletas.db:/app/bicicletas.db

  front:
    build: red_bicicletas